# Generated by Django 3.1.7 on 2021-03-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aq1',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='aq2',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='sq1',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='sq2',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
