# Generated by Django 3.1.7 on 2021-03-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitchen', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('security_question1', models.CharField(max_length=255)),
                ('answer_question1', models.CharField(max_length=255)),
                ('security_question2', models.CharField(max_length=255)),
                ('answer_question2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kitchen/')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('days', models.ManyToManyField(related_name='days', to='kitchen.Day')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen', to='kitchen.kitchen'),
        ),
    ]
